### ISSUE TITLE
Create a github issue template for comments, pr , etc

### ISSUE THREAD

**Issue by JoseRodrigues443** [sYnced7/StorageInstruments#1]
Create a github issue template for comments, pr , etc

![image](https://user-images.githubusercontent.com/16213184/82058368-91a8d380-96bc-11ea-8103-804abb3620bf.png)

**Comment by sYnced7** [comment]
Added. Thanks :)

**Comment by JoseRodrigues443** [comment]
![image](https://user-images.githubusercontent.com/16213184/83003513-55536c80-a006-11ea-8869-6affe4e5d376.png)

you added but not configured it
